name: Purge Main Page

concurrency: 
  group: wiki-bot-group
  cancel-in-progress: true

on:
  repository_dispatch:
    types: [Purge Main Page]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    steps:
      - name: Load Scripts
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Pywikibot
        run: pip install pywikibot

      - name: Run Bot
        uses: nick-fields/retry@v4
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: |
            echo "('TRCDBot', BotPassword('TRCDBot_AutoPurge', '${{ secrets.BOT_PASSWORD }}'))" > passwordfile
            chmod 600 passwordfile
            python bot.py

      - name: Save Report
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git config set advice.skippedCherryPicks false
          git add purge.log
          git commit -m "Update logs for $(date +%Y-%m-%d) [skip ci]" || exit 0
          git pull --rebase -X ours origin main
          git push origin main
